### ISSUE TITLE
No scrolling to package in Explorer View

### ISSUE THREAD

**Issue by JustPilz** [xicunyang/fe-jump#1] opened 2023-02-22 13:22 UTC
I use [node-modules-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.node-modules-jump)
It's better for me than [fe-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.fe-jump) because the extension adds an item to the context menu in Chinese, but I'm not Chinese speaker. And I'm not a fan of unnecessary elements :)

**So I have a problem:**
When you press ctrl + click, package.json opens fine. But there is no scrolling to package in Explorer View (left sidebar).

Thank you for great extension!

**Comment by xicunyang** [comment] 2023-02-22 15:21
Thank you so much for using it!
I am paying attention to this problem recently and found that it is caused by the update of vscode. Since 1.72.x, there seem to be various problems, including the problem that the TreeView cannot be automatically refreshed.
I have been investigating this problem for two days, and I have no good idea, until I asked about ChatGPT just now, it told me a very good idea! I just tried it, it can solve this problem!
I just released a new plug-in version, which is 1.0.9, you can go to update the latest version, and then restart vscode, no accident, it can work normally~

**Comment by xicunyang** [comment] 2023-02-22 15:21
> I use [node-modules-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.node-modules-jump) It's better for me than [fe-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.fe-jump) because the extension adds an item to the context menu in Chinese, but I'm not Chinese speaker. And I'm not a fan of unnecessary elements :)
> 
> **So I have a problem:** When you press ctrl + click, package.json opens fine. But there is no scrolling to package in Explorer View (left sidebar).
> 
> Thank you for great extension!

Thank you so much for using it!
I am paying attention to this problem recently and found that it is caused by the update of vscode. Since 1.72.x, there seem to be various problems, including the problem that the TreeView cannot be automatically refreshed.
I have been investigating this problem for two days, and I have no good idea, until I asked about ChatGPT just now, it told me a very good idea! I just tried it, it can solve this problem!
I just released a new plug-in version, which is 1.0.9, you can go to update the latest version, and then restart vscode, no accident, it can work normally~

**Comment by xicunyang** [comment] 2023-02-22 15:26
> I use [node-modules-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.node-modules-jump) It's better for me than [fe-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.fe-jump) because the extension adds an item to the context menu in Chinese, but I'm not Chinese speaker. And I'm not a fan of unnecessary elements :)
> 
> **So I have a problem:** When you press ctrl + click, package.json opens fine. But there is no scrolling to package in Explorer View (left sidebar).
> 
> Thank you for great extension!

> > I use [node-modules-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.node-modules-jump) It's better for me than [fe-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.fe-jump) because the extension adds an item to the context menu in Chinese, but I'm not Chinese speaker. And I'm not a fan of unnecessary elements :)
> > **So I have a problem:** When you press ctrl + click, package.json opens fine. But there is no scrolling to package in Explorer View (left sidebar).
> > Thank you for great extension!
> 
> Thank you so much for using it! I am paying attention to this problem recently and found that it is caused by the update of vscode. Since 1.72.x, there seem to be various problems, including the problem that the TreeView cannot be automatically refreshed. I have been investigating this problem for two days, and I have no good idea, until I asked about ChatGPT just now, it told me a very good idea! I just tried it, it can solve this problem! I just released a new plug-in version, which is 1.0.9, you can go to update the latest version, and then restart vscode, no accident, it can work normally~

Sorry, there is a problem with the plugin just now, I accidentally packaged the soft link function (I haven’t maintained this project for a long time, I am a little forgotten, hahaha), wait for 10 minutes, and a 1.0.10 version will be released Come out and install the latest version!

**Comment by xicunyang** [comment] 2023-02-22 17:04
> I use [node-modules-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.node-modules-jump) It's better for me than [fe-jump](https://marketplace.visualstudio.com/items?itemName=xicunyang.fe-jump) because the extension adds an item to the context menu in Chinese, but I'm not Chinese speaker. And I'm not a fan of unnecessary elements :)
> 
> **So I have a problem:** When you press ctrl + click, package.json opens fine. But there is no scrolling to package in Explorer View (left sidebar).
> 
> Thank you for great extension!

I fixed another small detail problem, please update to 1.0.11, I tested it and found no problem, if you have any problem, please report it in time~

**Comment by xicunyang** [comment] 2023-02-22 17:11
It has been fixed, you can see this commit record: https://github.com/xicunyang/fe-jump/commit/ef72d1b13f594217f8b50769bc20b1a6bbefedc8

**Closed as completed by xicunyang** 2023-02-22 17:11 UTC
Labels: bug

**Comment by JustPilz** [comment] 2023-02-22 23:46
It works great! Thanks for very quick response and fix!

**Comment by xicunyang** [comment] 2023-02-23 09:26
After today's investigation, I finally found a better repair method, which I briefly describe below:
1. First of all, the problem of not updating on the left is not a bug of vscode, but a new configuration item added after version 1.74.x, please see this link: https://code.visualstudio.com/updates /v1_74#_custom-explorer-autoreveal-logic, which describes the problem of "Custom Explorer autoreveal logic".

2. Yesterday’s emergency repair was actually a hack that added some logic, which is not very suitable, but it’s okay, and I don’t plan to change it back later. Keep it, and it doesn’t have much impact on performance in theory.

3. The modification in my extension will only be triggered when jumping from package.json, but it should be noted that if you enter the import dependency from the ts file, the target file cannot be located on the left side as well. For example, import * from "lodash", at this time you Ctrl + Click, and then click "lodash", the page jumps to the package.json of lodash, but the left side is still at the previous file.

So, in the end, I hope you can delete ""**/node_modules": true" according to the link above. This is the most scientific way to deal with it!

@JustPilz
